# Environment dimensions
AREA_WIDTH = 600
AREA_HEIGHT = 600

# Sensor and MC Parameters
NUM_SENSORS = 40
SENSOR_CAPACITY = 10800  # Joules (10.8 kJ)
MC_CAPACITY = 1000000   # Joules
MC_SPEED = 5  # m/s
CHARGING_RATE = 4.8  # Joules per second
MOVEMENT_COST_PER_M = 60  # Joules per meter
THRESHOLD_RATIO = 0.2    # Time window opens when energy < 20% of capacity
CHARGING_RADIUS = 60     # Radius in meters (increased from 2.8 to provide "good range")


CRITICAL_ENERGY_RATIO = 0.03  
CHARGING_INNER_ZONE = 0.4
CHARGING_MIDDLE_ZONE = 0.7
INNER_EFFICIENCY = 0.8
MIDDLE_EFFICIENCY = 0.6
OUTER_EFFICIENCY = 0.4
GRID_SEARCH_SIZE = 30
CHARGING_SEARCH_EXPANSION = 1.2
MIN_PRIORITY_THRESHOLD = 0.15
MIN_SENSORS_FOR_POSITION = 2
SCORE_IMPROVEMENT_FACTOR = 1.5
RETURN_THRESHOLD_RATIO = 0.15
CHARGE_ENERGY_ESTIMATE = 500